name: Rust Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch 📥
      uses: actions/checkout@v2

    - name: Run Tests 🧪
      run: cargo test --verbose

    - name: Use Node.js 📦
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Build GUI 🛠️
      run: |
        cd gui
        npm install
        npm run build
        
    - name: Install SSH Client 🛰️
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: build
