name: Rust Test

on: [ push, pull_request ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch 📥
      uses: actions/checkout@v2

    - name: Use Node.js 📦
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Run Rust Tests 🧪
      run: cargo test --verbose

    - name: Rust Node.js Tests 🧪
      run: |
        cd gui
        npm build
