name: Rust Test

on: [ push, pull_request ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch 📥
      uses: actions/checkout@v2

    - name: Use Node.js 📦
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install GUI Build Dependencies 📦
      run: |
        sudo apt-get update
        sudo apt-get install -y curl rsync
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Run Rust Tests 🧪
      run: cargo test --verbose

    - name: Run GUI Tests 🧪
      run: |
        wasm-pack build --release
        cd gui
        npm install
        npm run prod-build
